-- Lumenati — In-house booth-rent invoicing (the Square cutover piece)
-- Run in the Supabase SQL editor AFTER artists-schema.sql + payments-schema.sql.
--
-- Rent has been read from Square invoices; this brings it in-house. One row
-- per artist per month, generated by the daily job (or the Generate button on
-- the Rent page). Each invoice gets a Stripe pay link (payments.kind='rent');
-- the webhook marks the invoice paid when the payment settles. Square stays
-- the fallback read until these rows exist (the Rent page prefers in-house).

create table if not exists public.rent_invoices (
  id           uuid primary key default gen_random_uuid(),
  artist_id    text not null references public.artists(id) on delete cascade,
  period       text not null,                       -- 'YYYY-MM'
  amount_cents integer not null,
  due_date     date,
  payment_id   uuid references public.payments(id) on delete set null,
  status       text not null default 'pending',     -- pending | paid | void
  paid_at      timestamptz,
  created_at   timestamptz not null default now(),
  constraint rent_invoices_status_chk check (status in ('pending','paid','void')),
  constraint rent_invoices_period_chk check (period ~ '^\d{4}-\d{2}$')
);

create unique index if not exists rent_invoices_artist_period_idx
  on public.rent_invoices (artist_id, period);
create index if not exists rent_invoices_status_idx on public.rent_invoices (status, period desc);

-- ── RLS ── owner + bookkeeper run rent; an artist sees their own invoices.
alter table public.rent_invoices enable row level security;

drop policy if exists rent_invoices_books_all on public.rent_invoices;
create policy rent_invoices_books_all on public.rent_invoices for all
  using (public.my_role() in ('owner','bookkeeper'))
  with check (public.my_role() in ('owner','bookkeeper'));

drop policy if exists rent_invoices_artist_read on public.rent_invoices;
create policy rent_invoices_artist_read on public.rent_invoices for select
  using (artist_id = public.my_artist());
